### ISSUE TITLE
Sometimes index page doesn't load, recovers fine after a refresh

### ISSUE THREAD

**Issue by toadhats** [toadhats/node-blog-engine#7]
Sometimes the index page tries to render an article summary before the object is loaded properly. I can't reproduce it right now, but it happens maybe once per 50 page visits? Maybe I need to try using a proper node debugger for this one. 

I'm pretty sure the router won't try and render the page until the last object has been loaded... although potentially, the issue is that it's trying to render the page _while_ the last article object is being loaded (e.g. the rest are all done, but it chokes on the final one).

**Comment by toadhats** [comment]
Error text (not that it's anything special, more or less implies that the object hasn't been loaded yet)

```
TypeError: /Users/jonathan/Code/GitHub/node-blog-engine/views/index.jade:21
19|   ul
20|     each article in articles
21|       a(href='/'+article.path)
22|         +postSummary(article)
23|       hr
24|       

    Cannot read property 'path' of undefined
        at eval (eval at <anonymous> (/Users/jonathan/Code/GitHub/node-blog-engine/node_modules/jade/lib/index.js:218:8), <anonymous>:133:47)
        at eval (eval at <anonymous> (/Users/jonathan/Code/GitHub/node-blog-engine/node_modules/jade/lib/index.js:218:8), <anonymous>:169:4)
        at eval (eval at <anonymous> (/Users/jonathan/Code/GitHub/node-blog-engine/node_modules/jade/lib/index.js:218:8), <anonymous>:236:22)
        at res (/Users/jonathan/Code/GitHub/node-blog-engine/node_modules/jade/lib/index.js:219:38)
        at Object.exports.renderFile (/Users/jonathan/Code/GitHub/node-blog-engine/node_modules/jade/lib/index.js:380:38)
        at Object.exports.renderFile (/Users/jonathan/Code/GitHub/node-blog-engine/node_modules/jade/lib/index.js:370:21)
        at View.exports.__express [as engine] (/Users/jonathan/Code/GitHub/node-blog-engine/node_modules/jade/lib/index.js:417:11)
        at View.render (/Users/jonathan/Code/GitHub/node-blog-engine/node_modules/express/lib/view.js:126:8)
        at tryRender (/Users/jonathan/Code/GitHub/node-blog-engine/node_modules/express/lib/application.js:639:10)
        at EventEmitter.render (/Users/jonathan/Code/GitHub/node-blog-engine/node_modules/express/lib/application.js:591:3)
```

**Comment by toadhats** [comment]
Implementing the tag cloud functionality (as of d5b9be267ab34e2063b5f9c710add7883b0c9a12) makes this worse – the tag cloud generator crashes the app, rather than the jade template just failing to render. I still can't reproduce this when I want to. Worse, I still don't get why it's happening – all the logic that tries to do things with article objects happens in the callback _triggered by the last article being loaded_

**Comment by toadhats** [comment]
Realistically, unless I can get someone to very patiently look over the function responsible, the only real solution is going to be to rewrite the whole function in a better performing, stabler and more debuggable way – like with promises.

**Comment by toadhats** [comment]
It looks like it's the _first_ article that isn't getting loaded on time, not the last. I guess this teaches an important lesson about node's async bs: just because we're done with the 139th article, doesn't mean the first is finished.
